#!/opt/homebrew/bin/fish

##### Plugin Directory #####

set PLUGIN_DIR $CONFIG_DIR/plugins

##### Bar Appearance #####

sketchybar --bar position=top height=38 blur_radius=24 color=0x801a1a25

##### Changing Defaults #####

set default \
    padding_left=5 \
    padding_right=5 \
    icon.font="Hack Nerd Font:Bold:17.0" \
    label.font="Hack Nerd Font:Bold:14.0" \
    icon.color=0xffffffff \
    label.color=0xffffffff \
    background.color=0x40ffffff \
    background.corner_radius=5 \
    background.height=25 \
    icon.padding_left=4 \
    icon.padding_right=4 \
    label.padding_left=4 \
    label.padding_right=4

sketchybar --default $default

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

for spaceInfo in (yabai -m query --spaces | jq -cr '.[] | "\(.index),\(.label)"');
  echo $spaceInfo
  set infoFields (string split ',' $spaceInfo)
  set sid $infoFields[1]
  set label $infoFields[2]
  echo Field:
  echo $infoFields[1]
  echo $infoFields[2]
  
  set space \
      space=$sid \
      icon=$label \
      icon.padding_left=7 \
      icon.padding_right=7 \
      background.color=0x40ffffff \
      background.corner_radius=5 \
      background.height=25 \
      label.drawing=off \
      script="$PLUGIN_DIR/space.sh" \
      click_script="yabai -m space --focus $label"
    echo $space
  
  sketchybar --add space space.$sid left
  sketchybar --set space.$sid $space
end

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
